# Production overrides to disable GitHub metadata
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Explicitly set repository to avoid GitHub API calls
repository: aliasvault/aliasvault

# Set baseurl explicitly to avoid GitHub Pages detection
baseurl: ""

# Disable GitHub metadata
github: [metadata]